### PR TITLE
Fix rendering of LIMIT / OFFSET clauses in SQLAlchemy to work with version 1.3 and lower (fix #334)

### LINKED ISSUE #334: pyathena==2.9.3 with SQLAlchemy==1.3.24 cannot fetch table metadata
Hey,

I have pyathena==2.9.3 installed with SQLAlchemy==1.3.24 But I get this error "An error occurred while fetching table metadata
". Stack trace is as below. 

2022-06-21 06:31:38,258:DEBUG:botocore.hooks:Event needs-retry.athena.GetTableMetadata: calling handler <botocore.retryhandler.RetryHandler object at 0x7fd6fbef5280>
--
2022-06-21 06:31:38,258:DEBUG:botocore.retryhandler:No retry needed.
2022-06-21 06:31:38,267:ERROR:root:'Select' object has no attribute '_simple_int_clause'
Traceback (most recent call last):
File "/usr/local/lib/python3.8/site-packages/flask_appbuilder/api/__init__.py", line 85, in wraps
return f(self, *args, **kwargs)
File "/app/superset/views/base_api.py", line 112, in wraps
raise ex
File "/app/superset/views/base_api.py", line 109, in wraps
duration, response = time_function(f, self, *args, **kwargs)
File "/app/superset/utils/core.py", line 1468, in time_function
response = func(*args, **kwargs)
File "/app/superset/utils/log.py", line 245, in wrapper
value = f(*args, **kwargs)
File "/app/superset/databases/api.py", line 522, in table_metadata
table_info = get_table_metadata(database, table_name, schema_name)
File "/app/superset/databases/utils.py", line 91, in get_table_metadata
"selectStar": database.select_star(
File "/app/superset/models/core.py", line 486, in select_star
return self.db_engine_spec.select_star(
File "/app/superset/db_engine_specs/base.py", line 1126, in select_star
sql = database.compile_sqla_query(qry)
File "/app/superset/models/core.py", line 466, in compile_sqla_query
sql = str(qry.compile(engine, compile_kwargs={"literal_binds": True}))
File "<string>", line 1, in <lambda>
File "/usr/local/lib/python3.8/site-packages/sqlalchemy/sql/elements.py", line 481, in compile
return self._compiler(dialect, bind=bind, **kw)
File "/usr/local/lib/python3.8/site-packages/sqlalchemy/sql/elements.py", line 487, in _compiler
return dialect.statement_compiler(dialect, self, **kw)
File "/usr/local/lib/python3.8/site-packages/sqlalchemy/sql/compiler.py", line 592, in __init__
Compiled.__init__(self, dialect, statement, **kwargs)
File "/usr/local/lib/python3.8/site-packages/sqlalchemy/sql/compiler.py", line 322, in __init__
self.string = self.process(self.statement, **compile_kwargs)
File "/usr/local/lib/python3.8/site-packages/sqlalchemy/sql/compiler.py", line 352, in process
return obj._compiler_dispatch(self, **kwargs)
File "/usr/local/lib/python3.8/site-packages/sqlalchemy/sql/visitors.py", line 96, in _compiler_dispatch
return meth(self, **kw)
File "/usr/local/lib/python3.8/site-packages/sqlalchemy/sql/compiler.py", line 2201, in visit_select
text = self._compose_select_body(
File "/usr/local/lib/python3.8/site-packages/sqlalchemy/sql/compiler.py", line 2320, in _compose_select_body
text += self.limit_clause(select, **kwargs)
File "/usr/local/lib/python3.8/site-packages/pyathena/sqlalchemy_athena.py", line 90, in limit_clause
if limit_clause is not None and select._simple_int_clause(limit_clause):
AttributeError: 'Select' object has no attribute '_simple_int_clause'
Triggering query_id: 74
2022-06-21 06:31:38,613:INFO:superset.sqllab.command:Triggering query_id: 74
Failed to execute query '74' - 'None': 'NoneType' object has no attribute 'strip'
2022-06-21 06:31:38,649:ERROR:superset.views.core:Failed to execute query '74' - 'None': 'NoneType' object has no attribute 'strip'

### PR DESCRIPTION
**Pull request by laughingman7743**

### CODE REVIEW

**Comment by mdeshmu** [comment]
You are awesome @laughingman7743 

When can i expect this fix to be released?

**Comment by laughingman7743** [comment]
Already released as v2.9.4.
https://github.com/laughingman7743/PyAthena/releases/tag/v2.9.4
https://pypi.org/project/pyathena/2.9.4/
Please try to update and confirm that no errors occur.
